name: A Workflow
on: workflow_dispatch
jobs:
    job-one:
      runs-on: ubuntu-22.04
      steps:
        - name: Print Greeting
          run: echo "Hello-World"
        - name: Print Goodbye
          run: echo "See you"